# Project 13 -- Dwijen Chawra

## Question 1

In [3]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql


In [4]:
%sql sqlite:///flights_sample.db


In [48]:
%%bash

cd ~/tdm201/project13

cp /anvil/projects/tdm/data/flights/flights_sample.db .

sqlite3 flights_sample.db

.header on
SELECT * FROM flights LIMIT 5;

ALTER TABLE flights ADD COLUMN updated_at DATETIME DEFAULT '1970-01-01 00:00:00';
SELECT * FROM flights LIMIT 5;


CREATE TRIGGER update_updated_at
    AFTER UPDATE ON flights
    BEGIN
        UPDATE flights
        SET updated_at = CURRENT_TIMESTAMP
        WHERE rowid = new.rowid;
    END;

UPDATE flights SET Year = 5555 WHERE Year = 2007 AND Month = 1 AND DayofMonth = 1 AND DayOfWeek = 1 AND DepTime = 1225 AND Origin = 'SMF';

SELECT * FROM flights WHERE Year = 5555;

Year|Month|DayofMonth|DayOfWeek|DepTime|CRSDepTime|ArrTime|CRSArrTime|UniqueCarrier|FlightNum|TailNum|ActualElapsedTime|CRSElapsedTime|AirTime|ArrDelay|DepDelay|Origin|Dest|Distance|TaxiIn|TaxiOut|Cancelled|CancellationCode|Diverted|CarrierDelay|WeatherDelay|NASDelay|SecurityDelay|LateAircraftDelay
2007|1|1|1|1232|1225|1341|1340|WN|2891|N351|69|75|54|1|7|SMF|ONT|389|4|11|0||0|0|0|0|0|0
2007|1|1|1|1918|1905|2043|2035|WN|462|N370|85|90|74|8|13|SMF|PDX|479|5|6|0||0|0|0|0|0|0
2007|1|1|1|2206|2130|2334|2300|WN|1229|N685|88|90|73|34|36|SMF|PDX|479|6|9|0||0|3|0|0|0|31
2007|1|1|1|1230|1200|1356|1330|WN|1355|N364|86|90|75|26|30|SMF|PDX|479|3|8|0||0|23|0|0|0|3
2007|1|1|1|831|830|957|1000|WN|2278|N480|86|90|74|-3|1|SMF|PDX|479|3|9|0||0|0|0|0|0|0
Year|Month|DayofMonth|DayOfWeek|DepTime|CRSDepTime|ArrTime|CRSArrTime|UniqueCarrier|FlightNum|TailNum|ActualElapsedTime|CRSElapsedTime|AirTime|ArrDelay|DepDelay|Origin|Dest|Distance|TaxiIn|TaxiOut|Cancelled|CancellationCode|Diverted|CarrierDelay|WeatherDe

In [44]:
%%bash
sqlite3 flights_sample.db
SELECT * FROM flights WHERE Year = 5555;

5555|1|1|1|1225|1215|1816|1745|NW|398|N326US|231|210|195|31|10|SMF|MSP|1518|15|21|0||0|3|0|21|0|7|2022-12-09 06:53:33


## Question 2

In [40]:
%%bash
cp /anvil/projects/tdm/data/movies_and_tv/imdb.db $SCRATCH

cd $SCRATCH

sqlite3 imdb.db
-- Create a view called titles_with_ratings that has all of the information from the titles table 
-- It also includes the rating and votes from the ratings table.
-- The view should have the same columns as the titles table, plus the rating and votes columns from the ratings table.

CREATE VIEW titles_with_ratings AS
SELECT t.*, r.rating, r.votes FROM titles AS t INNER JOIN ratings AS r ON t.title_id = r.title_id;

SELECT * FROM titles_with_ratings LIMIT 5;

tt0000001|short|Carmencita|Carmencita|0|1894||1|Documentary,Short|5.7|1718
tt0000002|short|Le clown et ses chiens|Le clown et ses chiens|0|1892||5|Animation,Short|6|211
tt0000003|short|Pauvre Pierrot|Pauvre Pierrot|0|1892||4|Animation,Comedy,Romance|6.5|1480
tt0000004|short|Un bon bock|Un bon bock|0|1892||12|Animation,Short|6.1|124
tt0000005|short|Blacksmith Scene|Blacksmith Scene|0|1893||1|Comedy,Short|6.2|2283


Markdown notes and sentences and analysis written here.

## Question 3

In [50]:
%%bash

cd ~/tdm201/project13

sqlite3 flights_sample.db

BEGIN;
UPDATE flights SET Year = 7777 WHERE Year = 5555;
SELECT * FROM flights WHERE Year = 7777;

ROLLBACK;

SELECT * FROM flights WHERE Year = 7777;
SELECT * FROM flights WHERE Year = 5555;




7777|1|1|1|1225|1215|1816|1745|NW|398|N326US|231|210|195|31|10|SMF|MSP|1518|15|21|0||0|3|0|21|0|7|2022-12-09 07:06:50
5555|1|1|1|1225|1215|1816|1745|NW|398|N326US|231|210|195|31|10|SMF|MSP|1518|15|21|0||0|3|0|21|0|7|2022-12-09 07:05:35


the first print is when the flight with year 5555 is changed and then the next print statement is when the flight with year 7777 is reverted back to 5555.

## Question 4

In [65]:
%%bash

cd ~/tdm201/project13

sqlite3 flights_sample.db

SELECT Origin, AVG(Distance)
FROM flights
GROUP BY Origin


ABE|528.123837923171
ABI|158.0
ABQ|658.160054420446
ABY|146.0
ACK|209.105095541401
ACT|89.0
ACV|224.982954545455
ACY|688.315646258503
ADK|1075.94174757282
ADQ|252.0
AEX|337.576769025367
AGS|144.82239720035
AKN|368.110638297872
ALB|613.982960240561
ALO|166.0
AMA|357.817157252718
ANC|1232.19751961529
APF|540.0
ASE|244.783788878417
ATL|653.067599208411
ATW|324.797863731995
AUS|676.490845616757
AVL|420.746620726213
AVP|561.011764705882
AZO|174.013669205233
BDL|755.942532258559
BET|399.0
BFL|372.461020211742
BGM|461.831262939959
BGR|577.777560498656
BHM|537.661185468451
BIL|491.085641244141
BIS|439.536291600634
BJI|199.0
BLI|755.578231292517
BMI|340.794264043612
BNA|671.374848534469
BOI|548.162929415663
BOS|845.992214775561
BPT|79.0
BQK|238.0
BQN|1459.30656934307
BRO|308.0
BRW|504.202479338843
BTM|357.0
BTR|402.772397796463
BTV|474.422986600359
BUF|495.255929853487
BUR|529.143341712347
BWI|703.85664396398
BZN|584.290624403284
CAE|509.066979362101
CAK|528.891162292448
CDV|186.5
CEC|219.35545

I decided to experiment with the average function and see what the average distance per location was.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.